hh = User.create({username: "hollyhawthorth", email: "hollyh@email.com", password: "druidsrock"})
sa = User.create({username: "serynarweiniad", email: "seryna@email.com", password: "clericsrock"})
ts = User.create({username: "tealstagheart", email: "teals@email.com", password: "warlocksrock"})
oi = User.create({username: "opheliainkwell", email: "opheliai@email.com", password: "wizardsrock"})

hat = Project.create({name: "Mushroom Hat", category: "Apparel", knit_time: 5, user_id: hh.id})
bag = Project.create({name: "Bag of Holding", category: "Accessory", knit_time: 10, user_id: hh.id})
scarf = Project.create({name: "Celtic Cable Scarf", category: "Apparel", knit_time: 25, user_id: sa.id})
sweater = Project.create({name: "Feywild Sweater", category: "Apparel", knit_time: 40, user_id: ts.id})
blanket = Project.create({name: "Blanket of Warming", category: "Homegood", knit_time: 80, user_id: oi.id})
ornament = Project.create({name: "Ornament of Holiday Spirit", category: "Homegood", knit_time: 2, user_id: oi.id})

Yarn.create({name: "KnitPicks: Wool of the Andes", wieght: 4, color: "Oyster Heather", quantity: 1, project_id: hat.id})
Yarn.create({name: "KnitPicks: Wool of the Andes", wieght: 4, color: "White", quantity: 1, project_id: hat.id})
Yarn.create({name: "KnitPicks: Wool of the Andes", wieght: 4, color: "Red", quantity: 1, project_id: hat.id})
Yarn.create({name: "Lion Brand: 24/7 Cotton", wieght: 3, color: "Cafe Au Lait", quantity: 3, project_id: bag.id})
Yarn.create({name: "Lion Brand: Wool-Ease", wieght: 4, color: "Oatmeal", quantity: 3, project_id: scarf.id})
Yarn.create({name: "Lion Brand: Fisherman's Wool", wieght: 4, color: "Birch Tweed", quantity: 5, project_id: 4})
Yarn.create({name: "Wool and the Gang: Crazy Sexy Wool", wieght: 6, color: "Bronzed Olive", quantity: 8, project_id: blanket.id})
Yarn.create({name: "Lion Brand: Vanna's Choice", wieght: 4, color: "Terracotta", quantity: 1, project_id: ornament.id})
Yarn.create({name: "Lion Brand: Vanna's Choice", wieght: 4, color: "Mustard", quantity: 1, project_id: ornament.id})
